# Generated by Django 5.1.2 on 2024-10-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image5',
        ),
    ]
