# Generated by Django 5.1.2 on 2024-10-19 06:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_variant_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
    ]
