# Generated by Django 5.1.2 on 2024-10-19 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_variant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='ocation',
        ),
        migrations.AddField(
            model_name='variant',
            name='occation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='variant',
            name='fit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
    ]
