# Generated by Django 5.1.2 on 2024-10-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('address', models.TextField(null=True)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isBlocked', models.BooleanField(default=False)),
            ],
        ),
    ]
